# kubernetes/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dlp-analytics-secrets
  namespace: dlp-ns
type: Opaque # Стандартный тип секрета
data:
  # Для Backend
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tb25nby11c2VybmFtZTptb25nby1wYXNzd29yZEBob3N0L2RscF9hbmFseXRpY3NfZXhwYW5kZWQ/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5" # Пример: mongodb+srv://mongo-username:mongo-password@host/dlp_analytics_expanded?retryWrites=true&w=majority
  JWT_SECRET: "YnJvX3RoaXNfaXNfYV9zdXBlcl9zZWNyZXRfa2V5X2Zvcl9qd3RfdG9rZW5zX21ha2VfaXRfbG9uZ19hbmRfcmFuZG9tX2luX2t1YmVybmV0ZXM=" # Пример: bro_this_is_a_super_secret_key_for_jwt_tokens_make_it_long_and_random_in_kubernetes
  
  # Для MongoDB StatefulSet (если вы создаете пользователя/пароль через переменные окружения)
  MONGO_INITDB_ROOT_USERNAME: "cm9vdA==" # root
  MONGO_INITDB_ROOT_PASSWORD: "c2VjcmV0bW9uZ29wYXNzd29yZA==" # secretmongopassword

  # Потенциальные секреты для Redis (если Redis требует пароль)
  # REDIS_PASSWORD: "c2VjcmV0cmVkaXNwYXNzd29yZA==" # secretredispassword

  # Потенциальные секреты для Email сервиса
  # EMAIL_HOST: "c210cC5leGFtcGxlLmNvbQ==" # smtp.example.com
  # EMAIL_PORT: "NTg3" # 587
  # EMAIL_USER: "dXNlckBleGFtcGxlLmNvbQ==" # user@example.com
  # EMAIL_PASS: "ZW1haWxwYXNzd29yZA==" # emailpassword
  # EMAIL_FROM: "bm9yZXBseUBleGFtcGxlLmNvbQ==" # noreply@example.com

  # Секреты для Grafana (если вы хотите задать админский пароль через переменные)
  # GF_SECURITY_ADMIN_USER: "YWRtaW4=" # admin
  # GF_SECURITY_ADMIN_PASSWORD: "c2VjcmV0Z3JhZmFuYXBhc3N3b3Jk" # secretgrafanapassword